# parse_CV_extract_information_task:

# description: >
# Understand different CV format and identify the key information required to match it with the job role. Read through the entire CV and extract the information in the expected output. 

# expected_output: >
# A file with the candidate name in the front and in the format of CV_extrcation_format.

# CV_extrcation_format:
# {CV_extrcation_format}

match_and_shortlist_candidate_task:

  description: > 
      Run through each CV, evaluate and match the candidates to the best job requirement based on their qualification, skills, past experience and suitability. Shortlist the candidates for the assessment process.   

  JobRole:
  {job_role}

  Job Requirements:
  {job_requirements}

  expected_output: >
    A shortlist of candidates that matches with each job description.

interview_the_candidate_task:
  description: >
    Ask questions relevant to the job role based on the job requirements. Wait for the user response, if the answer does match well with the context of the question ask further question on the same topic. If not, probe deeper into the same question.
    
    Example:

    If the question related to finding duplicate for SQL 
    Candidate: I will 
    

  expected_output: >
    Raw transcript of questions and answers for each candidate. 

evaluation_and_reporting_task:
  description: >
    Create recruiter-friendly summary of performance and score candidate against predefined criteria. Shortlist recommendations based on scoring and send recommendation list by email.
    



